version: "3"
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
        env_file:
            - .env
    db:
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - .db/init.sql:/docker-entrypoint-initdb.d/init.sql
        env_file:
            - .env